export const DATA_REQUEST_API = 'DATA_REQUEST_API'
export const DATA_RECEIVE_API = 'DATA_RECEIVE_API'
export const DATA_MODIFY = 'DATA_MODIFY'
export const DATA_IS_LOADED = 'DATA_IS_LOADED'

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'